### ISSUE TITLE
Automatic reloading after editing?

### ISSUE THREAD

**Issue by kendonB** [mrob95/Breathe#2]
Would be neat to have automatic reloading going (without an engine restart) just like Caster 1.0.0.

**Comment by mrob95** [comment]
Going to look into this today, it shouldn't be too complicated but may well need to be implemented on the user side rather than in breathe. If that's the case then I'll just add a snippet to the documentation (which doesn't actually exist yet) which people can copy.

**Comment by mrob95** [comment]
Done, I think. Instructions are in the readme, you need to do a bit of work specifying which files you want imported but reloading by issuing a voice command seems to be working for me with natlink. I'm probably not going to pursue automatic reloading as I think it would require a significant increase in complexity, without much improvement in UX.

Please let me know if it doesn't work as you expect it to, or if the instructions are confusing, we're still very much in alpha  :).
